/// <reference path="../pb_data/types.d.ts" />

/**
 * The CPQ collections.
 *
 * This app used to be a dummy-data generator. It is now Configure/Price/Quote,
 * which is a different domain end to end, so this migration creates the seven
 * collections that domain needs and drops the three the old one used.
 *
 * **That deletes the old data.** `configs`, `datasets` and `script_templates`
 * go, along with everything in them. There is no CPQ meaning to migrate them
 * into — a generated dataset is not a quote — and leaving them behind would
 * mean three dead collections that every future migration has to keep
 * stepping around. Take a `GET /api/export` from the old app first if the
 * contents still matter.
 *
 * ## Shape
 *
 * Each collection has real columns for what the *database* has to do something
 * with — find by SKU, sort by name, filter by status, match an approver — and
 * one JSON field for the nested domain object the app reads whole. Option
 * groups, configuration rules, volume tiers, quote lines and totals are all
 * read and written in one piece, and spreading them across dozens of
 * PocketBase fields would buy no query that anything performs and cost a
 * migration every time the domain grew a feature.
 *
 * ## Access
 *
 * The rules below are the whole access-control story; the Bun server holds no
 * credentials and grants nothing. Three patterns:
 *
 *   owner only            accounts, pricing rules, approval rules
 *   owner or shared with  products, price books, proposal templates
 *   owner, shared, or an approver the quote is waiting on   quotes
 *
 * The last one is what lets somebody decide an approval without being given
 * anything else of yours — they can read and write exactly the quote they were
 * asked about, and a hook (rules/approvals.js) holds them to the approval
 * fields on the way through.
 *
 * Ids are supplied by the app (`prd_…`, `qte_…`) rather than autogenerated, so
 * they stay readable and type-tagged in the REST API, in exported files and in
 * the UI. That needs the system `id` field widened from PocketBase's fixed
 * 15-character default.
 */
migrate(
  app => {
    const users = app.findCollectionByNameOrId("users");

    /** App-supplied id: `<prefix>_<hex>`, still autogeneratable as a fallback. */
    const idField = {
      type: "text",
      name: "id",
      system: true,
      primaryKey: true,
      required: true,
      min: 3,
      max: 40,
      pattern: "^[a-z0-9_]+$",
      autogeneratePattern: "[a-z0-9]{15}",
    };

    const created = { type: "autodate", name: "created", onCreate: true, onUpdate: false };
    const updated = { type: "autodate", name: "updated", onCreate: true, onUpdate: true };

    const ownerField = () => ({
      type: "relation",
      name: "owner",
      required: false,
      maxSelect: 1,
      collectionId: users.id,
      cascadeDelete: true, // closing an account takes its data with it
    });

    /** Read-only recipients. Maintained only by pb_hooks/lib/sharing.js. */
    const sharedWithField = () => ({
      type: "relation",
      name: "sharedWith",
      required: false,
      maxSelect: 50,
      collectionId: users.id,
      cascadeDelete: false, // a deleted account drops off the list
    });

    const MINE = "owner = @request.auth.id";
    // `?=` is "any of": the relation holds many ids and one must match.
    const MINE_OR_SHARED = `${MINE} || sharedWith.id ?= @request.auth.id`;
    const SIGNED_IN = '@request.auth.id != ""';

    /** Owner-only: nothing here is passed around. */
    const privateRules = {
      listRule: MINE,
      viewRule: MINE,
      createRule: SIGNED_IN,
      updateRule: MINE,
      deleteRule: MINE,
    };

    /** Readable by the people it was shared with; writable only by its owner. */
    const sharedRules = {
      listRule: MINE_OR_SHARED,
      viewRule: MINE_OR_SHARED,
      createRule: SIGNED_IN,
      updateRule: MINE,
      deleteRule: MINE,
    };

    const index = (collection, name, columns) =>
      `CREATE INDEX \`idx_${collection}_${name}\` ON \`${collection}\` (${columns})`;

    /* ------------------------------ customers ----------------------------- */

    const priceBooks = new Collection({
      name: "price_books",
      type: "base",
      ...sharedRules,
      fields: [
        idField,
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "text", name: "description", required: false, max: 2000 },
        { type: "text", name: "currency", required: true, min: 3, max: 3 },
        { type: "bool", name: "isDefault", required: false },
        { type: "bool", name: "active", required: false },
        { type: "text", name: "validFrom", required: false, max: 10 },
        { type: "text", name: "validTo", required: false, max: 10 },
        // One entry is a handful of numbers; 4 MB holds tens of thousands.
        { type: "json", name: "entries", required: false, maxSize: 4194304 },
        ownerField(),
        sharedWithField(),
        created,
        updated,
      ],
      indexes: [index("price_books", "owner", "`owner`")],
    });
    app.save(priceBooks);

    const accounts = new Collection({
      name: "accounts",
      type: "base",
      ...privateRules,
      fields: [
        idField,
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "text", name: "contactEmail", required: false, max: 200 },
        { type: "text", name: "currency", required: true, min: 3, max: 3 },
        {
          type: "relation",
          name: "priceBook",
          required: false,
          maxSelect: 1,
          collectionId: priceBooks.id,
          // Deleting a price book leaves its customers in place, pointing at
          // nothing, which falls back to the default book.
          cascadeDelete: false,
        },
        { type: "json", name: "details", required: false, maxSize: 65536 },
        ownerField(),
        created,
        updated,
      ],
      indexes: [index("accounts", "owner_name", "`owner`, `name`")],
    });
    app.save(accounts);

    /* ------------------------------- products ----------------------------- */

    const products = new Collection({
      name: "products",
      type: "base",
      ...sharedRules,
      fields: [
        idField,
        { type: "text", name: "sku", required: true, min: 1, max: 60 },
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "text", name: "description", required: false, max: 5000 },
        { type: "text", name: "family", required: false, max: 120 },
        { type: "number", name: "listPrice", required: false, min: 0 },
        { type: "number", name: "cost", required: false, min: 0 },
        { type: "text", name: "currency", required: true, min: 3, max: 3 },
        { type: "bool", name: "active", required: false },
        // Option groups, rules, bundle components, tiers and attributes.
        { type: "json", name: "definition", required: false, maxSize: 2097152 },
        ownerField(),
        sharedWithField(),
        created,
        updated,
      ],
      indexes: [
        // A SKU identifies one product *per account*: two people using one
        // instance each have their own catalogue.
        "CREATE UNIQUE INDEX `idx_products_owner_sku` ON `products` (`owner`, `sku`)",
        index("products", "family", "`family`"),
      ],
    });
    app.save(products);

    /* -------------------------------- policy ------------------------------ */

    const pricingRules = new Collection({
      name: "pricing_rules",
      type: "base",
      ...privateRules,
      fields: [
        idField,
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "number", name: "priority", required: false, min: 0 },
        { type: "bool", name: "active", required: false },
        { type: "json", name: "definition", required: false, maxSize: 65536 },
        ownerField(),
        created,
        updated,
      ],
      indexes: [index("pricing_rules", "owner_priority", "`owner`, `priority`")],
    });
    app.save(pricingRules);

    const approvalRules = new Collection({
      name: "approval_rules",
      type: "base",
      ...privateRules,
      fields: [
        idField,
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "number", name: "level", required: false, min: 1, max: 20 },
        { type: "text", name: "approverEmail", required: false, max: 200 },
        { type: "bool", name: "active", required: false },
        { type: "json", name: "definition", required: false, maxSize: 65536 },
        ownerField(),
        created,
        updated,
      ],
      indexes: [index("approval_rules", "owner_level", "`owner`, `level`")],
    });
    app.save(approvalRules);

    /* ------------------------------ documents ----------------------------- */

    const proposalTemplates = new Collection({
      name: "proposal_templates",
      type: "base",
      ...sharedRules,
      fields: [
        idField,
        // Matches MAX_TEMPLATE_NAME_LENGTH / MAX_TEMPLATE_BODY_LENGTH in
        // src/lib/proposal.ts, which reject first with a better message.
        { type: "text", name: "name", required: true, min: 1, max: 120 },
        { type: "text", name: "format", required: false, max: 20 },
        { type: "text", name: "body", required: false, max: 200000 },
        ownerField(),
        sharedWithField(),
        created,
        updated,
      ],
      indexes: [index("proposal_templates", "owner", "`owner`")],
    });
    app.save(proposalTemplates);

    /* -------------------------------- quotes ------------------------------ */

    const quotes = new Collection({
      name: "quotes",
      type: "base",
      fields: [
        idField,
        { type: "text", name: "number", required: true, min: 1, max: 40 },
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "text", name: "status", required: true, max: 20 },
        { type: "number", name: "version", required: false, min: 1 },
        // `supersedes` points at this same collection and is added below, once
        // saving the collection has given it an id to point at.
        {
          type: "relation",
          name: "priceBook",
          required: false,
          maxSelect: 1,
          collectionId: priceBooks.id,
          cascadeDelete: false,
        },
        { type: "text", name: "currency", required: true, min: 3, max: 3 },
        { type: "text", name: "validUntil", required: false, max: 10 },
        { type: "number", name: "lineCount", required: false, min: 0 },
        // Customer snapshot, term, discount, tax, notes.
        { type: "json", name: "header", required: false, maxSize: 65536 },
        // See MAX_QUOTE_BYTES in src/server/db.ts, which rejects an oversized
        // quote first with a sentence about the quote.
        { type: "json", name: "lines", required: false, maxSize: 4194304 },
        { type: "json", name: "totals", required: false, maxSize: 65536 },
        { type: "json", name: "approvals", required: false, maxSize: 262144 },
        {
          // The accounts this quote is currently waiting on. A relation rather
          // than the email in `approvals`, because the read rule has to match
          // on it and rules match ids.
          type: "relation",
          name: "approvers",
          required: false,
          maxSelect: 20,
          collectionId: users.id,
          cascadeDelete: false,
        },
        // Plain dates, not autodates: these are set when the app decides
        // something happened, not on every write.
        { type: "date", name: "sentAt", required: false },
        { type: "date", name: "decidedAt", required: false },
        ownerField(),
        sharedWithField(),
        created,
        updated,
      ],
      indexes: [
        "CREATE UNIQUE INDEX `idx_quotes_owner_number` ON `quotes` (`owner`, `number`)",
        index("quotes", "owner_status", "`owner`, `status`"),
      ],
    });

    app.save(quotes);

    // Now that it has an id, the self-reference can be added.
    quotes.fields.add(
      new Field({
        type: "relation",
        name: "supersedes",
        required: false,
        maxSelect: 1,
        collectionId: quotes.id,
        // Deleting a superseded quote leaves its revision in place, pointing
        // at nothing — the revision is the document that matters.
        cascadeDelete: false,
      }),
    );

    const MINE_SHARED_OR_APPROVER = `${MINE_OR_SHARED} || approvers.id ?= @request.auth.id`;
    quotes.listRule = MINE_SHARED_OR_APPROVER;
    quotes.viewRule = MINE_SHARED_OR_APPROVER;
    quotes.createRule = SIGNED_IN;
    // An approver may write the quote they were asked about — and only its
    // approval fields, which pb_hooks/rules/approvals.js enforces.
    quotes.updateRule = `${MINE} || approvers.id ?= @request.auth.id`;
    quotes.deleteRule = MINE;
    app.save(quotes);

    /* ------------------------ the generator's remains ---------------------- */

    // Datasets reference configs, so they have to go first.
    for (const name of ["script_templates", "datasets", "configs"]) {
      try {
        app.delete(app.findCollectionByNameOrId(name));
      } catch (err) {
        // Never existed, or already gone. Either way there is nothing to drop.
      }
    }
  },
  app => {
    // Down: drop the CPQ collections in dependency order. The generator's
    // collections are not recreated — the migrations that made them are still
    // in this directory and will run again on a fresh volume.
    for (const name of [
      "quotes",
      "proposal_templates",
      "approval_rules",
      "pricing_rules",
      "products",
      "accounts",
      "price_books",
    ]) {
      try {
        app.delete(app.findCollectionByNameOrId(name));
      } catch (err) {
        // Already gone.
      }
    }
  },
);
